# Change these first
owner: Streckenkunde
repo: Monitoring

sites:
  - name: Webseite
    url: https://streckenkunde.digital
  - name: API
    url: https://streckenkunde.digital/api

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /Monitoring
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Monitoring - Streckenkunde Digital"
  introMessage: Übersicht der laufenden Dienste für Streckenkunde Digital
  navbar:
    - title: Status
      href: /
